// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class ALoginformtestsTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void emailLoginaut() {
    driver.Navigate().GoToUrl("https://www.litres.ru/");
    driver.FindElement(By.CssSelector("div:nth-child(1) > .Tab-modules__tab_o4eJ7 path")).Click();
    driver.FindElement(By.Name("email")).Click();
    driver.FindElement(By.Name("email")).SendKeys("Shigaleva");
    driver.FindElement(By.CssSelector(".AuthContent-module__content_2LDzv")).Click();
    driver.FindElement(By.CssSelector(".Button-module__button_primary_2FaKg .Button-module__textContainer_1I67-")).Click();
    {
      var element = driver.FindElement(By.CssSelector(".Button-module__button_primary_2FaKg .Button-module__textContainer_1I67-"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    {
      var element = driver.FindElement(By.TagName("body"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element, 0, 0).Perform();
    }
    driver.FindElement(By.Name("email")).Click();
    driver.FindElement(By.Name("email")).SendKeys("shigaleva.alexandra@gmail.com");
    driver.FindElement(By.CssSelector(".Button-module__button_primary_2FaKg")).Click();
    driver.FindElement(By.Name("pwd")).SendKeys("Sas");
    driver.FindElement(By.CssSelector(".Button-module__button_2hpyT")).Click();
    {
      var element = driver.FindElement(By.CssSelector(".Button-module__button_2hpyT"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    {
      var element = driver.FindElement(By.TagName("body"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element, 0, 0).Perform();
    }
    driver.FindElement(By.CssSelector(".AuthContent-module__content_2LDzv")).Click();
    driver.FindElement(By.CssSelector(".ControlInput-module__input__placeholder_36_vX")).Click();
    driver.FindElement(By.CssSelector(".ControlInput-module__input_1GZ-3")).Click();
    driver.FindElement(By.Name("pwd")).Click();
    driver.FindElement(By.Name("pwd")).SendKeys("Sashakakashka11");
    driver.FindElement(By.CssSelector(".Button-module__button_2hpyT")).Click();
    driver.Close();
  }
  [Test]
  public void exitacc() {
    driver.Navigate().GoToUrl("https://www.litres.ru/");
    driver.FindElement(By.CssSelector(".ProfileButton-module__profileButton__logo_LWN_F")).Click();
    driver.FindElement(By.CssSelector(".Menu__exit_TFDJG > span")).Click();
    driver.Close();
  }
  [Test]
  public void otheraut() {
    driver.Navigate().GoToUrl("https://www.litres.ru/");
    driver.FindElement(By.CssSelector("div:nth-child(1) > .Tab-modules__tab_o4eJ7 .Tab-modules__tab__title_nqb1J")).Click();
    driver.FindElement(By.CssSelector(".Button-module__button_tertiary_-NpmH .Button-module__textContainer_1I67-")).Click();
    driver.FindElement(By.CssSelector(".Socials-module__socials__link_2Hfo5:nth-child(4) > .Socials-module__socials__link_icon_siDof")).Click();
    driver.Close();
  }
}
